sudo: required
dist: trusty
language: node_js
node_js:
- '6.1'
branches:
  only:
  - master
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    code_climate:
      repo_token: CODECLIMATE_REPO_TOKEN
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g gulp
- npm install -g bower
- npm install -g codeclimate-test-reporter
- bower install
script:
after_script:
- codeclimate-test-reporter < reports/coverage/lcov.info
deploy:
  provider: heroku
  api_key:
    secure: HEROKU_KEY
  app: beercalc-app
  on:
    repo: WandersonAlves/beercalc
