sudo: required
dist: trusty
language: node_js
node_js:
  - "6.1"
branches:
  only:
  - master
addons:
  apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
  code_climate:
        repo_token: 3e1b7ee31d2428a76f79e2e71d75540299ec27adf489048256aa16b2f1afd355
cache:
  directories:
    - node_modules
    - bower_components
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g gulp
  - npm install -g bower
  - gulp build
  # - /home/travis/build/WandersonAlves/neweb/node_modules/protractor/bin/webdriver-manager update
script:
  # Add Karma and Protractor commands like the ones above
  #- protractor spec/web-conf.js
  #- protractor spec/mobile-conf.js
after_script:
  - codeclimate-test-reporter < lcov.info
