sudo: required
dist: trusty
language: node_js
node_js:
- '6.1'
branches:
  only:
  - development
  - master
notifications:
  slack: $SLACK_KEY
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    code_climate:
      repo_token: CODECLIMATE_REPO_TOKEN
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower
- npm install -g codeclimate-test-reporter
- bower install
script:
after_script:
- codeclimate-test-reporter < reports/coverage/lcov.info
before_deploy: echo "" > .gitignore
deploy:
  provider: heroku
  skip_cleanup: true
  app:
    development: beercalc-development
    master: beercalc-app
  on:
    repo: WandersonAlves/beercalc
  api_key:
    secure: $HEROKU_KEY
